### ISSUE TITLE
".left" element width out of control

### ISSUE THREAD

**Issue by fdev31** [scorpion-26/gBar#78]
I wanted to remove the general background and have one per "part" (left, center, right).

```css
.left {
    background-color: $bg;
    border-radius: 16px;
}

.center {
    background-color: $bg;
    border-radius: 16px;
}

.right {
    background-color: $bg;
    border-radius: 16px;
}
```
unfortunately the left "area" seem to take all the free space available.

Setting "width" or "max-width" leads to a segfault.

In the following screenshot, center & right parts are as expected, but I can't make the left side look similar...
 
![image](https://github.com/scorpion-26/gBar/assets/238622/1da96951-322d-4c17-a6e7-df316a0203b1)

Edit: seems related to the CenterTime option... so maybe a warning/error is preferable than a segfault :)
